container:
  image: xeffyr/termux-advanced-builder:latest
  cpu: 4
  memory: 8


build_task:
  timeout_in: 120m

  environment:
    TERMUX_MAKE_PROCESSES: 4
    matrix:
      - TERMUX_ARCH: aarch64
        LEGACY_ANDROID: false
      - TERMUX_ARCH: aarch64
        LEGACY_ANDROID: true
      - TERMUX_ARCH: arm
        LEGACY_ANDROID: false
      - TERMUX_ARCH: arm
        LEGACY_ANDROID: true
      - TERMUX_ARCH: i686
        LEGACY_ANDROID: false
      - TERMUX_ARCH: i686
        LEGACY_ANDROID: true
      - TERMUX_ARCH: x86_64
        LEGACY_ANDROID: false
      - TERMUX_ARCH: x86_64
        LEGACY_ANDROID: true

  # Build modified packages.
  build_script: |
    bash ./scripts/cirrus-ci_dispatcher.sh

  # Make built packages downloadable from web UI.
  output_artifacts:
    path: "./termux-packages/debs/*.deb"


# Upload packages to Bintray.
publish_task:
  only_if: $CIRRUS_BRANCH == 'master'

  timeout_in: 60m

  depends_on:
    - build

  environment:
    BINTRAY_USERNAME: ENCRYPTED[5977e6c0f069d0bc9be4ed09044d59835767a5c71c541cbe47cd56736cc43f5191a9291bbc3031a9267f0be105651f25]
    BINTRAY_API_KEY: ENCRYPTED[04f4ee0fc194ca2f94959a623388d4c3ae1bf874e8fa876f79b2659fc9e8f6fea952275e97f2d022e43e2ab6c67d1198]
    matrix:
      - LEGACY_ANDROID: false
      - LEGACY_ANDROID: true

  upload_script: |
    bash ./scripts/cirrus-ci_dispatcher.sh --upload
